language: cpp

sudo: required

branches:
    only:
      - master

stages:
  - "Building"
  - name: "Deployment"
    if: branch = master

env:
  - BUILD_TYPE=release
              
install:
  - source .travis/${TRAVIS_OS_NAME}/install.sh
