language: cpp 
matrix:
  include:
    compiler: gcc
before_install:
  - sudo apt-get install -y doxygen
script:
  - doxygen -g
  - git push -f -q https://ImyaPolzovatelyaPolzovatel:$GITHUB_API_KEY@https://github.com/ImyaPolzovatelyaPolzovatel/Doxygen.git > /dev/null
branches:
  only:
    - master
