language: cpp 
matrix:
  include:
    compiler: gcc
before_install:
  - sudo apt-get install -y doxygen
script:
  - doxygen -g
  - git config --global user.name "ImyaPolzovatelyaPolzovatel"
  - git config --global user.email "2019103620@pnu.edu.ru"
  - git add -A
  - git commit -am "Update doc from Travis CI"
  - git push https://ImyaPolzovatelyaPolzovatel:@https://github.com/ImyaPolzovatelyaPolzovatel/Doxygen.git
branches:
  only:
    - master
